name: Setup ucacher
description: Installs the ucacher binary
branding:
  icon: "sunrise"
  color: "green"
author: Earthly technologies
inputs:
  aws_access_key:
    description: "AWS_ACCESS_KEY_ID used for S3 file storage cache"
  aws_secret_access_key:
    description: "AWS_SECRET_ACCESS_KEY used for S3 file storage cache"
  file_storage_uri:
    description: "URI of the file storage endpoint, for example: s3://<region>/<bucket-name>"
  db_uri:
    description: "Database URI. Only Postgres supported for now: postgres[ql]://[username[:password]@][host[:port],]/database[?parameter_list]"
runs:
  using: "composite"
  steps:
    - name: Install ucacher binary
      run: |
        echo "Downloading binary from ${{ inputs.binary-url }}"
        curl -L https://github.com/earthly/react/raw/refs/heads/nacho/test-ignore/.github/ucacher -o /usr/local/bin/ucacher
        chmod +x /usr/local/bin/ucacher;
        echo "Binary installed at /usr/local/bin/ucacher"
      shell: bash

    - name: Set ucacher environment
      run: |
          echo "AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }}" >> $GITHUB_ENV
          echo "UCACHER_DB_URI=${{ inputs.db_uri }}" >> $GITHUB_ENV
          echo "UCACHER_STORAGE=${{ inputs.file_storage_uri }}" >> $GITHUB_ENV
          echo "UCACHER_INSTRUMENTER=strace" >> $GITHUB_ENV
          echo "UCACHER_SHOW_IO=true" >> $GITHUB_ENV
          echo "FORCE_COLOR=1" >> $GITHUB_ENV
          echo "LOG_LEVEL=debug" >> $GITHUB_ENV
      shell: bash
